### ISSUE TITLE
[BUG] Parameter .item method not working 

### ISSUE THREAD

**Issue by mokrueger** [evereux/pycatia#197] opened 2024-03-12 15:53 UTC
**Describe the bug**
in pycatia/pycatia/knowledge_interfaces/parameters.py

The parameters.item will fail with Attribute error "... object has no attribute 'value'"
<img width="532" alt="image" src="https://github.com/evereux/pycatia/assets/59337243/05997f1d-b04d-4658-bcc4-9aff722734a8">

since the com_object will not have .value but .Value

**To Reproduce**
Access parameters with .item

**Expected behavior**
Get the proper item

**Comment by mokrueger** [comment] 2024-03-12 17:24
Addressed in https://github.com/evereux/pycatia/pull/198

**Comment by evereux** [comment] 2024-03-15 18:49
Again, I can't reproduce the issue here.

This works for me on a `List` type parameter.

```python

from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument

caa = catia()
part_document = PartDocument(caa.active_document.com_object)
part = part_document.part
parameters = part.parameters

print(parameters.item(2).value)
```

I do like what you've done coding wise though!

**Comment by evereux** [comment] 2024-03-17 16:34
Closing as 0.6.7 now has these changes implemented.

**Closed by evereux** 2024-03-17 16:34 UTC
