### ISSUE TITLE
Bug in Pycatia 0.7.2

### ISSUE THREAD

**Issue by hosseintfr** [evereux/pycatia#224] opened 2024-07-07 07:06 UTC
There is a bug in Pycatia 0.7.2. When you want to open a file in Catia using Pycatia, sometimes you will see this error in Catia: Document cannot be read!
This error would not occured if you use Pycatia 0.6.9.
Please fix it.

Thanks a lot dear @evereux .

**Comment by evereux** [comment] 2024-07-07 13:30
Duplicate of #225.

**Closed by evereux** 2024-07-07 13:30 UTC
